### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by mickhansen**
To test locally:

```
npm install
npm run build
npm link
cd example
npm install
npm link @criipto/verify-express
npm start
```

### CODE REVIEW

**Comment by sgryt** [comment]
@mickhansen Looks great, but too much code to meaningfully review - will try it out asap instead, but don’t let that block your progress if you had more work planned.

**Comment by mickhansen** [comment]
@sgryt It's pretty much done for an initial version. Just wanted a second pair of eyes on the README and example.

**Comment by sgryt** [comment]
Kicking the tires now, logout with Passport shows a CSP-related error on the console 

image

**Comment by sgryt** [comment]
Passport login #2 using MitID (accessing protected route) ends up on

image

**Comment by sgryt** [comment]
We should probably add a "disable breakpoints when using MitID" in the index page (part that says "follow along on the console"(

**Comment by sgryt** [comment]
The timestamp validation error: Clock skew of 5-10 minutes should be used (if not already)

**Comment by sgryt** [comment]
Login with plain express shows errors on console (and an empty json literal on the page after login): 

image

**Comment by sgryt** [comment]
Blocked request to the jwt path:

image

Bearer token is: 
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkIxMTQ5QkM4MEMyNUY4MTZEODVCMjdFMTMwNUYzRkQ1NTMwNkUzRUYifQ.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuY3JpaXB0by5pZCIsImF1ZCI6InVybjpteTphcHBsaWNhdGlvbjppZGVudGlmaWVyOjkxMzQiLCJpZGVudGl0eXNjaGVtZSI6InNlYmFua2lkIiwiYXV0aGVudGljYXRpb250eXBlIjoidXJuOmdybjphdXRobjpzZTpiYW5raWQ6YW5vdGhlci1kZXZpY2U6cXIiLCJhdXRoZW50aWNhdGlvbm1ldGhvZCI6InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlNvZnR3YXJlUEtJIiwiYXV0aGVudGljYXRpb25pbnN0YW50IjoiMjAyMi0xMS0xNlQwNzowNzowNC4wMjJaIiwibmFtZWlkZW50aWZpZXIiOiIyMjM1NDIwNmQ5ZmY0YzUwYjdiZTJkZmEzOTk1MWM2MiIsInN1YiI6InsyMjM1NDIwNi1kOWZmLTRjNTAtYjdiZS0yZGZhMzk5NTFjNjJ9Iiwic2Vzc2lvbmluZGV4IjoiZTRlNTdmMGQtYzYwYi00ZWJkLTkxOGEtODY1NTM3MDZkZWJlIiwic3NuIjoiMTk2ODAyMDIwNTc1IiwibmFtZSI6IlRlcm5lIFBhdWxzZW4iLCJnaXZlbm5hbWUiOiJUZXJuZSIsImdpdmVuX25hbWUiOiJUZXJuZSIsInN1cm5hbWUiOiJQYXVsc2VuIiwiZmFtaWx5X25hbWUiOiJQYXVsc2VuIiwiaXBhZGRyZXNzIjoiNzkuMTQyLjIzMi4xMjYiLCJjb3VudHJ5IjoiU0UiLCJpYXQiOjE2Njg1ODI0MjQsIm5iZiI6MTY2ODU4MjQyNCwiZXhwIjoxNjY4NTgzNjI0fQ.mejt02I0exqMPfBIjlDU1ISexMnVGmAgl8hL1qPpqy9yNQiOVgGAhn_auEyFvbOJIUHEVOO0J9B7AWGYAB3Qd6ZWXXOTgwGEDbrdrQgQu0HJvpHNJcV7XOWLULRtr0ma6aFyxR6qcKOoLtATbH6OxdevAwex4PqJBjaYOM3fMXJWecaE0OQjzXDdxSv3v7sPypBhdwX65mKkyepoVnLYIC2UpmkfsahSpo42tGoRZk1m6QN5Ip7-bzZ6hZ5VRZv4VfYYMHXbFql_lcT41IWOp78vViMdZOMP2QenzciQwRJqyvR0NG3BB0iKcHdRLZj-REmYYol0LtsTeLrZIjnfaA
```

**Comment by sgryt** [comment]
> We should probably add a "disable breakpoints when using MitID" in the index page (part that says "follow along on the console")

**Comment by sgryt** [comment]
If I start an Incognito browser and try the "access proctected route" link, I get acccess.
Some state mechanics ?

**Comment by mickhansen** [comment]
> If I start an Incognito browser and try the "access proctected route" link, I get acccess. Some state mechanics ?

Which protected route specifically? JWT or Redirect/Session?

**Comment by mickhansen** [comment]
> Kicking the tires now, logout with Passport shows a CSP-related error on the console
> 
> image

Hmm, cannot reproduce and does appear unrelated.
Edit: Can reproduce, but the error appears to be from the runtime?

**Comment by mickhansen** [comment]
> The timestamp validation error: Clock skew of 5-10 minutes should be used (if not already)

5 minute clock skew added as a default.

**Comment by mickhansen** [comment]
> Login with plain express shows errors on console (and an empty json literal on the page after login):
> 
> image

Example will now show when there is a HTTP error

**Comment by mickhansen** [comment]
> Blocked request to the jwt path:
> 
> image
> 
> Bearer token is:
> 
> ```
> eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkIxMTQ5QkM4MEMyNUY4MTZEODVCMjdFMTMwNUYzRkQ1NTMwNkUzRUYifQ.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuY3JpaXB0by5pZCIsImF1ZCI6InVybjpteTphcHBsaWNhdGlvbjppZGVudGlmaWVyOjkxMzQiLCJpZGVudGl0eXNjaGVtZSI6InNlYmFua2lkIiwiYXV0aGVudGljYXRpb250eXBlIjoidXJuOmdybjphdXRobjpzZTpiYW5raWQ6YW5vdGhlci1kZXZpY2U6cXIiLCJhdXRoZW50aWNhdGlvbm1ldGhvZCI6InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlNvZnR3YXJlUEtJIiwiYXV0aGVudGljYXRpb25pbnN0YW50IjoiMjAyMi0xMS0xNlQwNzowNzowNC4wMjJaIiwibmFtZWlkZW50aWZpZXIiOiIyMjM1NDIwNmQ5ZmY0YzUwYjdiZTJkZmEzOTk1MWM2MiIsInN1YiI6InsyMjM1NDIwNi1kOWZmLTRjNTAtYjdiZS0yZGZhMzk5NTFjNjJ9Iiwic2Vzc2lvbmluZGV4IjoiZTRlNTdmMGQtYzYwYi00ZWJkLTkxOGEtODY1NTM3MDZkZWJlIiwic3NuIjoiMTk2ODAyMDIwNTc1IiwibmFtZSI6IlRlcm5lIFBhdWxzZW4iLCJnaXZlbm5hbWUiOiJUZXJuZSIsImdpdmVuX25hbWUiOiJUZXJuZSIsInN1cm5hbWUiOiJQYXVsc2VuIiwiZmFtaWx5X25hbWUiOiJQYXVsc2VuIiwiaXBhZGRyZXNzIjoiNzkuMTQyLjIzMi4xMjYiLCJjb3VudHJ5IjoiU0UiLCJpYXQiOjE2Njg1ODI0MjQsIm5iZiI6MTY2ODU4MjQyNCwiZXhwIjoxNjY4NTgzNjI0fQ.mejt02I0exqMPfBIjlDU1ISexMnVGmAgl8hL1qPpqy9yNQiOVgGAhn_auEyFvbOJIUHEVOO0J9B7AWGYAB3Qd6ZWXXOTgwGEDbrdrQgQu0HJvpHNJcV7XOWLULRtr0ma6aFyxR6qcKOoLtATbH6OxdevAwex4PqJBjaYOM3fMXJWecaE0OQjzXDdxSv3v7sPypBhdwX65mKkyepoVnLYIC2UpmkfsahSpo42tGoRZk1m6QN5Ip7-bzZ6hZ5VRZv4VfYYMHXbFql_lcT41IWOp78vViMdZOMP2QenzciQwRJqyvR0NG3BB0iKcHdRLZj-REmYYol0LtsTeLrZIjnfaA
> ```

Could this have been due to clock skew?

**Comment by sgryt** [comment]
> > Blocked request to the jwt path:
> > image
> > Bearer token is:
> > ```
> > eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkIxMTQ5QkM4MEMyNUY4MTZEODVCMjdFMTMwNUYzRkQ1NTMwNkUzRUYifQ.eyJpc3MiOiJodHRwczovL3NhbXBsZXMuY3JpaXB0by5pZCIsImF1ZCI6InVybjpteTphcHBsaWNhdGlvbjppZGVudGlmaWVyOjkxMzQiLCJpZGVudGl0eXNjaGVtZSI6InNlYmFua2lkIiwiYXV0aGVudGljYXRpb250eXBlIjoidXJuOmdybjphdXRobjpzZTpiYW5raWQ6YW5vdGhlci1kZXZpY2U6cXIiLCJhdXRoZW50aWNhdGlvbm1ldGhvZCI6InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlNvZnR3YXJlUEtJIiwiYXV0aGVudGljYXRpb25pbnN0YW50IjoiMjAyMi0xMS0xNlQwNzowNzowNC4wMjJaIiwibmFtZWlkZW50aWZpZXIiOiIyMjM1NDIwNmQ5ZmY0YzUwYjdiZTJkZmEzOTk1MWM2MiIsInN1YiI6InsyMjM1NDIwNi1kOWZmLTRjNTAtYjdiZS0yZGZhMzk5NTFjNjJ9Iiwic2Vzc2lvbmluZGV4IjoiZTRlNTdmMGQtYzYwYi00ZWJkLTkxOGEtODY1NTM3MDZkZWJlIiwic3NuIjoiMTk2ODAyMDIwNTc1IiwibmFtZSI6IlRlcm5lIFBhdWxzZW4iLCJnaXZlbm5hbWUiOiJUZXJuZSIsImdpdmVuX25hbWUiOiJUZXJuZSIsInN1cm5hbWUiOiJQYXVsc2VuIiwiZmFtaWx5X25hbWUiOiJQYXVsc2VuIiwiaXBhZGRyZXNzIjoiNzkuMTQyLjIzMi4xMjYiLCJjb3VudHJ5IjoiU0UiLCJpYXQiOjE2Njg1ODI0MjQsIm5iZiI6MTY2ODU4MjQyNCwiZXhwIjoxNjY4NTgzNjI0fQ.mejt02I0exqMPfBIjlDU1ISexMnVGmAgl8hL1qPpqy9yNQiOVgGAhn_auEyFvbOJIUHEVOO0J9B7AWGYAB3Qd6ZWXXOTgwGEDbrdrQgQu0HJvpHNJcV7XOWLULRtr0ma6aFyxR6qcKOoLtATbH6OxdevAwex4PqJBjaYOM3fMXJWecaE0OQjzXDdxSv3v7sPypBhdwX65mKkyepoVnLYIC2UpmkfsahSpo42tGoRZk1m6QN5Ip7-bzZ6hZ5VRZv4VfYYMHXbFql_lcT41IWOp78vViMdZOMP2QenzciQwRJqyvR0NG3BB0iKcHdRLZj-REmYYol0LtsTeLrZIjnfaA
> > ```
> 
> Could this have been due to clock skew?

Absolutely, but that was not visible in neither the response nor on the node console. 
Perhaps we should add some targeted logging for errors in the node host ?

**Comment by sgryt** [comment]
> > If I start an Incognito browser and try the "access proctected route" link, I get acccess. Some state mechanics ?
> 
> Which protected route specifically? JWT or Redirect/Session?

Not sure, the one triggered by this link: 
image

**Comment by mickhansen** [comment]
> Absolutely, but that was not visible in neither the response nor on the node console.
> Perhaps we should add some targeted logging for errors in the node host ?

I added `DEBUG=criipto/verify-express` to the default start command so it should log JWT validation errors to the console running `npm start`.

**Comment by mickhansen** [comment]
> > > If I start an Incognito browser and try the "access proctected route" link, I get acccess. Some state mechanics ?
> > 
> > 
> > Which protected route specifically? JWT or Redirect/Session?
> 
> Not sure, the one triggered by this link: image

I was unable to reproduce this. Can you try again?

**Comment by sgryt** [comment]
OK, all links work as expected now, and I also tested various combinations of login-logout across passport/plain cases.

Idea: A navigate-to-frontpage HTML element from the /*/protected/ pages, to ease testing/debugging

**Pull request merged**
